import org.blockchain_innovation.factom.client.api.EntryApi;
import org.blockchain_innovation.factom.client.api.FactomdClient;
import org.blockchain_innovation.factom.client.api.WalletdClient;
import org.blockchain_innovation.factom.client.impl.EntryApiImpl;
import org.blockchain_innovation.factom.client.impl.FactomdClientImpl;
import org.blockchain_innovation.factom.client.impl.OfflineWalletdClientImpl;
import org.blockchain_innovation.factom.iot_sas.IoTSASClientImpl;
import org.blockchain_innovation.factom.iot_sas.IoTSASPort;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    private static final IoTSASClientImpl SAS = new IoTSASClientImpl();
    private static final IoTSASPort PORT = new IoTSASPort();
    private static final FactomdClient FACTOMD_LIENT = new FactomdClientImpl();
    private static final WalletdClient SIGNING_CLIENT = new OfflineWalletdClientImpl();
    private static final EntryApi ENTRY_API = new EntryApiImpl();


    static {
        PORT.setup("/dev/serial0", 57600);
        SAS.setPort(PORT);
        ENTRY_API.setFactomdClient(FACTOMD_LIENT).setWalletdClient(SIGNING_CLIENT);

        System.out.println(String.format("Public hardware EC address: %s", SAS.getPublicECAddress()));


    }


    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
